set -g prefix C-Space
set -g escape-time 100
set -g history-limit 8000
set -g base-index 0
setw -g pane-base-index 0
set -g mouse on

# Window management
bind C new-window
bind e choose-window
bind X confirm-before -p "kill-window #W? (y/n)" kill-window

# Pane management
bind w split-window -h
bind W split-window -v

# Other bindings
bind R source-file ~/.tmux.conf \; display-message "Config reloaded!"
bind g copy-mode
bind G paste-buffer

set -g status-position bottom
set -g status-interval 1
set -g status-left "#{session_name} "
set -g status-left-length 50
set -g status-right "#{host} %Y-%m-%d %H:%M"
set -g status-right-length 50

# Plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Theme
set -g @plugin 'arcticicestudio/nord-tmux'

# Other plugins
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'tmux-plugins/tmux-open'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-copycat'
set -g @plugin 'tmux-plugins/tmux-sidebar'

# Initialize TMUX plugin manager
# Keep this line at the very bottom of tmux.conf
run '~/.tmux/plugins/tpm/tpm'

