#!/bin/bash

CURRENT_MODE=$(ps -o args -p "$(pgrep "sxhkd")" | awk -F'/' '{print $NF}' | sed '/^COMMAND$/d')
LABYRDIR="$HOME/.config/sxhkd"
VIM_MODE="$LABYRDIR/normal"     
VIDEO_MODE="$LABYRDIR/video"
AUDIO_MODE="$LABYRDIR/audio"
NETWORK_MODE="$LABYRDIR/network"
TASK_MODE="$LABYRDIR/task"
INSERT_MODE="$LABYRDIR/ins"
CONFIG_MODE="$LABYRDIR/config"

ressx() {
    pkill sxhkd 
    if pgrep -x "sxhkd" >/dev/null; then
 	echo "keybinding strata established. ^^"
    else
	echo "applying keybinding strata."
    	sxhkd -c "$1" > /dev/null 2>&1 &
	sleep 0.5 
	kill -SIGUSR1 sxhkd &
    fi
}

case "$1" in

    -v)
	notify-send "$VIM_MODE"
        ressx "$VIM_MODE" 
        ;;

    -i)

	notify-send "$INSERT_MODE"
        ressx "$INSERT_MODE" 
        ;;

    -V)

        notify-send "$VIDEO_MODE"  
        ressx "$VIDEO_MODE"  
     	;;

    -a) 

        notify-send "$VIDEO_MODE"  
        ressx "$AUDIO_MODE" 
     	;;

    -t)

        notify-send "$TASK_MODE" 
        ressx "$TASK_MODE" 
     	;;
    
    -n) 

        notify-send "$NETWORK_MODE" 
        ressx "$NETWORK_MODE" 
	;;

    -c) 
        notify-send "$CONFIG_MODE" 
        ressx "$CONFIG_MODE" 
	;;

    -e)
	wm -t wm -EE $LABYRDIR/$CURRENT_MODE
	lb -i
        ;;

    -H)
        echo "$CURRENT_MODE" &
        ;;

    -h) 

        echo "Usage: $0 -v | -i | -d | -n | -a | -t | -s"
        echo "  -v: VIM MODE ENABLE"
        echo "  -i: INSERT MODE ENABLE"
        echo "  -a: AUDIO MODE ENABLE"
        echo "  -V: VIDEO MODE ENABLE"
	echo "  -n: NETWORK MODE ENABLE"
        echo "  -t: TASK MODE ENABLE" 
        echo "  -H: SHOW CURRENT MODE"
        ;; 

    *)
        ressx "$VIM_MODE" 
        ;; 

esac
