#!/bin/bash
LABYRTERM="urxvt"
LABYRMU="$LABYRTERM -e ncmpcpp"
LABYREDIT="$LABYRTERM -e nvim"
LABYRWEB="mullvad-browser"
LABYREDIT="nvim"
LABYRCHAT="equibop"
LABYRMAIL="claws-mail"
WIDIR="$HOME/.nhk"
WIDIRCFGDIR="$HOME/.nhk/xt/cfg"

wideps() { # ignore this 
    case "$1" in
#        "Gentoo")
#        sudo emerge --ask dev-vcs/git dev-lang/python dev-python/pipx x11-libs/cairo x11-libs/libx11 x11-libs/libxft x11-libs/libxinerama x11-libs/pango x11-libs/gtk+:4 dev-util/pkgconf gobject-introspection x11-misc/dunst app-arch/p7zip media-gfx/feh sys-apps/lf x11-misc/xsel media-video/mpv media-sound/mpd media-sound/ncmpcpp sys-apps/htop app-misc/redshift x11-terms/rxvt-unicode x11-misc/rofi x11-apps/dmenu x11-misc/slock dev-libs/yajl media-libs/freetype media-gfx/shotgun x11-misc/xclipboard media-fonts/terminus-font x11-misc/ueberzug app-multiplexers/tmux x11-libs/libwnck:3 net-news/newsboat app-editors/neovim x11-apps/xrandr x11-apps/xsetroot media-sound/pulsemixer media-sound/pasystray mail-client/claws-mail media-gfx/shotgun && \
#	git clone https://github.com/huijunchen9260/dmenufm ~/dmenufm && \
#	cd ~/dmenufm && \
#	make && sudo make install && \
#	cd ~/ && \
#	git clone https://github.com/rvaiya/warpd.git && \ 
#	cd warpd/ && \
#	make && sudo make install && \
#	cd ~/ && \
#	rm -rf warpd/ && \
#	curl -LOS "https://raw.githubusercontent.com/whoisYoges/emojimenu/master/allemojis.txt" && \
#	curl -LOS "https://raw.githubusercontent.com/whoisYoges/emojimenu/master/emojimenu" && \
#	chmod +x emojimenu && \
#	sudo mkdir -p /usr/share/emojimenu && \
#	sudo mv allemojis.txt /usr/share/emojimenu/allemojis.txt && \
#	sudo mv emojimenu /usr/local/bin/emojimenu && \
#	git clone https://github.com/darkhz/bluetuith && \
#	cd bluetuith && \ 
#	go build main.go -o bluetuith-bin && \
#	mv bluetuith-bin /usr/bin/bluetuith && \
#	cd ~/ && \ 
#	git clone https://github.com/kspi/dmenu-frecency && \
#	sudo mv dmenu-frecency/dmenu-frecency /usr/bin/ && \
#	curl -fsSL https://dwmbar.robinhirst.qzz.io/install.sh | bash && \
#	cargo install hacksaw && \
#	echo 'complete. dependencies are installed.'
#	;;
#
#        "Debian")
#        sudo apt install build-essential libxi-dev libxinerama-dev libxft-dev libxfixes-dev libxtst-dev libx11-dev libcairo2-dev libxkbcommon-dev libwayland-dev xorg-dev xserver-xorg libyajl-dev libpango1.0-dev libpangoxft-1.0-0 libwnck-3-0 libwnck-3-common libfreetype6 libzip2 findutils suckless-tools xclip xz-utils golang wmctrl mpd mpv xsel feh lf ncmpcpp brightnessctl redshift rofi dmenu slock newsboat neovim xinit git libgirepository1.0-dev gcc pkg-config python3-dev gir1.2-gtk-4.0 pipx gtk-layer-shell grim ibpam0g-dev libxcb-xkb-dev xauth claws-mail && \
#	git clone https://github.com/huijunchen9260/dmenufm ~/dmenufm && \
#	cd ~/dmenufm && \
#	make  -j4 && sudo make install && \
#	cd ~/ && \
#	git clone https://github.com/rvaiya/warpd.git && \ 
#	cd warpd/ && \
#	make -j4 && sudo make install && \
#	cd ~/ && \
#	rm -rf warpd/ && \
#	curl -LOS "https://raw.githubusercontent.com/whoisYoges/emojimenu/master/allemojis.txt" && \
#	curl -LOS "https://raw.githubusercontent.com/whoisYoges/emojimenu/master/emojimenu" && \
#	chmod +x emojimenu && \
#	sudo mkdir -p /usr/share/emojimenu && \
#	sudo mv allemojis.txt /usr/share/emojimenu/allemojis.txt && \
#	sudo mv emojimenu /usr/local/bin/emojimenu && \
#	git clone https://github.com/darkhz/bluetuith && \
#	cd bluetuith && \ 
#	go build main.go -o bluetuith-bin && \
#	mv bluetuith-bin /usr/bin/bluetuith && \
#	cd ~/ && \ 
#	git clone https://github.com/kspi/dmenu-frecency && \
#	sudo mv dmenu-frecency/dmenu-frecency /usr/bin/ && \
#	curl -fsSL https://dwmbar.robinhirst.qzz.io/install.sh | bash && \
#	cargo install hacksaw && \
#	[ $XDG_SESSION_TYPE = "x11" ] sudo apt install && \
#	pipx ensurepath && \
#	pipx install git+https://github.com/AlfredoSequeida/hints.git && \
#	echo 'complete. dependencies are installed.'
#            ;;
#
#        "Fedora")
#            sudo dnf groupinstall "Development Tools" && sudo dnf install libX11-devel libXft-devel libXinerama-devel xorg-x11-server-Xorg xorg-x11-xinit git gcc gobject-introspection-devel cairo-gobject-devel pkg-config python3-devel gtk4 pipx pasystray kernel-devel pam-devel libxcb-devel zig xorg-x11-xauth xorg-x11-server brightnessctl gtk-layer-shell grim pulsemixer && \ 
#	    [ $XDG_SESSION_TYPE = "x11" ] && \ 
#            pipx ensurepath && \
#            pipx install git+https://github.com/AlfredoSequeida/hints.git && \
#	    pipx install calcure
#	    git clone https://github.com/huijunchen9260/dmenufm ~/dmenufm && \
#	    cd ~/dmenufm && \
#	    make  -j4 && sudo make install && \
#	    cd ~/ && \
#	    git clone https://github.com/rvaiya/warpd.git && \ 
#	    cd warpd/ && \
#	    make -j4 && sudo make install && \
#	    cd ~/ && \
#	    rm -rf warpd/ && \
#	    curl -LOS "https://raw.githubusercontent.com/whoisYoges/emojimenu/master/allemojis.txt" && \
#	    curl -LOS "https://raw.githubusercontent.com/whoisYoges/emojimenu/master/emojimenu" && \
#	    chmod +x emojimenu && \
#	    sudo mkdir -p /usr/share/emojimenu && \
#	    sudo mv allemojis.txt /usr/share/emojimenu/allemojis.txt && \
#	    sudo mv emojimenu /usr/local/bin/emojimenu && \
#	    git clone https://github.com/darkhz/bluetuith && \
#	    cd bluetuith && \ 
#	    go build main.go -o bluetuith-bin && \
#	    mv bluetuith-bin /usr/bin/bluetuith && \
#	    cd ~/ && \ 
#	    git clone https://github.com/kspi/dmenu-frecency && \
#	    sudo mv dmenu-frecency/dmenu-frecency /usr/bin/ && \
#	    curl -fsSL https://dwmbar.robinhirst.qzz.io/install.sh | bash && \
#	    cargo install hacksaw && \
#	    [ $XDG_SESSION_TYPE = "x11" ] sudo apt install && \
#	    pipx ensurepath && \
#	    pipx install git+https://github.com/AlfredoSequeida/hints.git && \
#	    echo 'complete. dependencies are installed.'
#            ;;
#        "Alpine")
#            apk add build-base libx11-dev libxft-dev libxinerama-dev xorg-server xinit
#            ;;
#        "Slackware")
#            slackpkg install gcc make autoconf automake libX11 libXft libXinerama xorg-server xinit
#            ;;
#        "OpenBSD")
#            pkg_add gmake autoconf automake libX11 libXft libXinerama xorg-server xinit
#            ;;
#        "FreeBSD")
#            sudo pkg install gcc gmake autoconf automake libX11 libXft libXinerama xorg-server xorg-xinit
#            ;;
#        "Void")
#            sudo xbps-install -S base-devel libX11-devel libXft-devel libXinerama-devel xorg-server xorg-xinit
#            ;;
#        "NixOS")
#            nix-env -iA nixos.gcc nixos.gnumake nixos.autoconf nixos.automake nixos.libX11 nixos.libXft nixos.libXinerama nixos.xorg.xorgserver nixos.xorg.xinit
#            ;;
#        "OpenSUSE")
#            sudo zypper install -t pattern devel_basis && sudo zypper install libX11-devel libXft-devel libXinerama-devel xorg-x11-server xorg-x11-xinit
#            ;;
	"Arch") 
            sudo pacman -S base-devel cairo libx11 libxft libxinerama git python pango pkgconf gobject-introspection lf xsel htop brightnessctl redshift rxvt-unicode rofi nvim libwnck3 yajl freetype2 shotgun xorg-xclipboard terminus-font ueberzug tmux webkit2gtk-4.1 gcr tmux xorg-xsetroot --noconfirm
	    git clone https://aur.archlinux.org/yay.git
	    cd yay/ 
	    makepkg -si 
	    yay -S warpd-git dmenufm-git bluetuith-git nitrogen dmenu-frecency pulsemixer pasystray-git hacksaw-git shotgun --noconfirm 
            ;;
#
#	"DSKIP")
#		pass	
#		;;
#        *)
#            echo "Unsupported distribution or package manager."
#            exit 1
#            ;;
    esac
}

case "$1" in

    -e)
     if [[ $# -gt 1 ]]; then
	$LABYREDIT "${@:2}" &
     else 
	$LABYRCHAT &
     fi
        exec $LABYREDIT {0:$2 &
        ;;

    -c)
     if [[ $# -gt 1 ]]; then
	$LABYRCHAT "${@:2}" &
     else 
	$LABYRCHAT &
     fi
        ;;

    -t)
     if [[ $# -gt 1 ]]; then
	$LABYRTERM -e "${@:2}" &
     else 
	$LABYRTERM &
     fi
     ;;

    -m) 

     if [[ $# -gt 1 ]]; then
	$LABYRMU -e "${@:2}" &
     else 
	$LABYRMU &
     fi
        ;;
	
    -g)
	
	URL=$(echo -e "" | dmenu -i -f -fn 'Terminus:pixelsize=10' -nb black -nf white -sb white -sf black -p "::git")
	notify-send "GIT: '$URL'"
	
	if [ -z "$URL" ]; then
	    notify-send "GIT: NONE"
	    exit 1
	fi
	
	REPO=""
	DIR=""
	

	if [[ "$URL" =~ ^https?://(github|gitea|codeberg|gitlab)\.com/(.*)/(.*)\.git$ ]]; then
	    REPO="${BASH_REMATCH[3]}"   
	    DIR="${BASH_REMATCH[2]}"    
	elif [[ "$URL" =~ ^([^/]+)/([^/]+)$ ]]; then
	    DIR="${BASH_REMATCH[1]}"    
	    REPO="${BASH_REMATCH[2]}"    
	    URL="https://github.com/${DIR}/${REPO}.git"  
	else
	    notify-send "GIT: [URL] OR [[NAME]/[REPO]]." & 
	    exit 1
	fi
	
	GITDIR="$(dmenufm -t -p)/$REPO"
	

	if [[ -d "$GITDIR" ]]; then
	    notify-send "GIT: [DIR_EXI]" &
	    exit 1
	fi
	
	# Attempt to clone the repository
	if git clone "$URL" "$GITDIR"; then
	    notify-send "GIT: $REPO [CLONED]" &
	else
	    notify-send "GIT: $REPO [CLFAIL]." & 
	    exit 1
	fi
	;;

	-d)


	MONITOR=$(xrandr --query | grep " connected" | awk '{print $1}')
	PRIMARY=$(xrandr --query | grep " connected primary" | awk '{print $1}')
	
	SEL=$(echo "$MONITOR" | dmenu -i -fn 'Terminus:pixelsize=10:antialias=true' -nb black -nf white -sb white -sf black -p "::disp")
	[ -z "$SEL" ] && exit 0
	
	ACTION=$(echo -e "direction\nref.rate\nscale" | dmenu -i -fn 'Terminus:pixelsize=10:antialias=true' -nb black -nf white -sb white -sf black -p "::action")
	[ -z "$ACTION" ] && exit 0
	
	case "$ACTION" in
	    direction)
	        POSITION=$(echo -e "Left\nRight\nAbove\nBelow\nMirror\nOnly" | dmenu -i -fn 'Terminus:pixelsize=10:antialias=true' -nb black -nf white -sb white -sf black -p "::pos")
	        [ -z "$POSITION" ] && exit 0
	        case "$POSITION" in
	            Left|Right|Above|Below) xrandr --output "$SEL" --auto "--${POSITION,,}-of" "$PRIMARY" ;;
	            Mirror) xrandr --output "$SEL" --auto --same-as "$PRIMARY" ;;
	            Only) xrandr --output "$SEL" --auto && for m in $MONITOR; do [ "$m" != "$SEL" ] && xrandr --output "$m" --off; done ;;
	        esac
	        ;;
	    "ref.rate")
	        RATES=$(xrandr --query | grep -A 100 "^$SEL connected" | grep -oP '\d+\.\d+(?=\*)?' | sort -u)
	        [ -z "$RATES" ] && exit 0
	        RATE=$(echo "$RATES" | dmenu -i -fn 'Terminus:pixelsize=10' -nb black -nf white -sb white -sf black -p "::rate")
	        [ -z "$RATE" ] && exit 0
	        xrandr --output "$SEL" --rate "$RATE"
	        ;;
	    scale)
	        SCALE_OPTION=$(echo -e "custom\n0.5x\n0.75x\n1.0x (Normal)\n1.25x\n1.5x\n2.0x" | dmenu -i -fn 'Terminus:pixelsize=10:antialias=true' -nb black -nf white -sb white -sf black -p "::scale")
	        [ -z "$SCALE_OPTION" ] && exit 0
	        
	        case "$SCALE_OPTION" in
	            "custom value")
	                CUSTOM=$(echo "" | dmenu -i -fn 'Terminus:pixelsize=10:antialias=true' -nb black -nf white -sb white -sf black -p "::value")
	                [ -z "$CUSTOM" ] && exit 0
	                xrandr --output "$SEL" --scale "$CUSTOM"
	                ;;
	            *)
	                SCALE=$(echo "$SCALE_OPTION" | grep -oP '^\d+\.?\d*')
	                xrandr --output "$SEL" --scale "$SCALE"
	                ;;
	        esac
	        ;;
	esac
    ;;

    -b)
	#while true; do
	    QRY=$(echo "" | dmenu -i -fn 'Terminus:pixelsize=10' -nb black -nf white -sb white -sf black -p "::url")
	
	    if [[ ! -z $QRY ]]; then
	        if echo "$QRY" | grep -qE "^(http|https)://"; then
	    	    TOROPT=$(echo -e "clearweb\ntor" | dmenu -i -fn 'Terminus:pixelsize=10' -nb black -nf white -sb white -sf black -p "::brw")
	            if [[ "$TOROPT" == "tor" ]]; then
	                torb "$QRY" &
	            else
	                $LABYRWEB "$QRY" &
	            fi
	        else
	            OPT4WB="$(echo -e "src\nurl" | dmenu -i -fn 'Terminus:pixelsize=10' -nb black -nf white -sb white -sf black -p "::opt")"
	            if [[ $OPT4WB == "src" ]]; then
			TOROPT=$(echo -e "clearweb\ntor" | dmenu -i -fn 'Terminus:pixelsize=10' -nb black -nf white -sb white -sf black -p "::brw")
	                if [[ "$TOROPT" == "tor" ]]; then
	                    torb "https://duckduckgo.com/search?q=$(echo "$QRY" | tr ' ' '+')" &
	                else
	                    $LABYRWEB "https://duckduckgo.com/search?q=$(echo "$QRY" | tr ' ' '+')" &
	                fi
	            elif [[ $OPT4WB == "url" ]]; then
	                if [[ "$TOROPT" == "tor" ]]; then
	                    torb "https://$QRY" & 
	                else
	                    $LABYRWEB "https://$QRY" & 
	                fi
	            fi
	        fi
	    else 
	        echo 'no query.'
		$LABYRWEB &
	        break
	    fi
    #done
	;;
	
    -w)
	#WP="$WIDIR/wp.png"
	#feh $WP --bg-fill &
	nitrogen --restore & 
        ;;

    -se)
	FILE="$HOME/.config/widow/.urlquery"
	
	if [ ! -f $FILE ]; then
	    touch $FILE
	fi
	
	FILEOPT=$(cat $FILE)
	
	OPTIONS="
	[
	${FILEOPT}
	[ \"+\", \"\" ],
	[ \"-\",  \"\" ]
	]
	"
	
	OBJ_LENGTH=$(echo $OPTIONS | jq length)
	OBJ_MENU=$(echo $OPTIONS | jq -r ".[][0]" | dmenu -i -fn 'Terminus:pixelsize=10' -nb black -nf white -sb white -sf black -p "::src")
	OBJ_QRY=$(echo "" | dmenu -i -fn 'Terminus:pixelsize=10' -nb black -nf white -sb white -sf black -p "::query")
	OBJ_KEYWORDS=$(echo "$OBJ_QRY" | tr " " "+")
	OBJ_SELECTED=$(echo "$OBJ_MENU" | cut -d' ' -f1)
	
	main() {
	    for i in $(seq 0 $((OBJ_LENGTH - 1))); do
	        if [ "$OBJ_SELECTED" = "+" ]; then
	            PREFIXMENU=$(echo "" | dmenu -i -fn 'Terminus:pixelsize=10' -nb black -nf white -sb white -sf black -p "::prfx[a]" <&-)
	            URLQUERY=$(echo "" | dmenu -fn 'Terminus:pixelsize=10' -nb black -nf white -sb white -sf black -p "::url[b]" <&-)
	            if [ ! -z "$PREFIXMENU" ]; then
	                echo "[ \"$PREFIXMENU\", \"$URLQUERY\" ]," >> $FILE
	            fi
	
	        elif [ "$OBJ_SELECTED" = "-" ]; then
	            OBJ_MENU=$(echo "$OPTIONS" | jq -r ".[][0]" | head -n -2 | dmenu -fn 'Terminus:pixelsize=10' -nb black -nf white -sb white -sf black -i -p "::del")
	            sed -i "/$OBJ_MENU/d" $FILE
	        fi
	        
	        if [ "$OBJ_SELECTED" = "$(echo "$OPTIONS" | jq -r --arg i "$i" '.[($i|tonumber)][0]')" ]; then
	            URLQUERY=$(echo "$OPTIONS" | jq -r --arg i "$i" '.[($i|tonumber)][1]')
	            KEYWORDS=$(echo "$OBJ_KEYWORDS")
	            xdg-open "${URLQUERY}${KEYWORDS}" 2> /dev/null
	        fi
	    done
	}
	
	main
	;;

    -sf)
	
        shotgun - | xclip -selection clipboard -t image/png
        filename=${filename:-$(date +%s)} && \
        mkdir -p $WIDIR/s/
        shotgun $WIDIR/s/"$filename.png"
        ;;

    -ss)

        selection=$(hacksaw -f "-i %i -g %g")
        shotgun $selection - | xclip -selection clipboard -t image/png
        filename=${filename:-$(date +%s)} && \
        mkdir -p $WIDIR/s/
        shotgun $selection $WIDIR/s/"$filename.png"
        ;;


   -sv)

    	dir=$WIDIR/widow/s/video/
    	current=$(date +%F_%H-%M-%S)
    	
    	mkdir -p "$dir"
    	hacksaw | {
    	    IFS=+x read -r w h x y
    	
    	    w=$((w + w % 2))
    	    h=$((h + h % 2))
    	
    	    $LABYRTERM -e ffmpeg \
    	        -v 16            \
    	        -r 30            \
    	        -f x11grab       \
                -s "${w}x${h}"   \
    	        -i ":0.0+$x,$y"  \
    	        -preset slow     \
    	        -c:v libx264        \
    	        -pix_fmt yuv420p \
    	        -crf 20          \
    	        -f pulse -i default \
    	        "$dir/$current.mp4" & \
		
    		}
	;;

   -ar)

   	   directory=$WIDIR/ar/
   	   date=$(date +%F_%H-%M-%S)
	   mkdir -p $directory
           $LABYRTERM -e ffmpeg -f pulse -i default "$directory/$date".wav

    	;;

   -T) 
	   wm -t $LABYREDIT $WIDIR/src/.nhktutorial & 
	   ;; 

   -P) 
	   OPT=$(echo "" | dmenu -fn 'Terminus:pixelsize=10' -nb black -nf white -sb white -sf black -i -p "::del")
	   if [[ -z $QRY ]]; then
		   $LABYRTERM -e $PKGMAN $QRY 
	   fi
	   ;;
   
   -pk) 
         sudo cp -rv /usr/bin/wm $WIDIR/yr/
         sudo cp -rv /usr/bin/lb $WIDIR/yr/
	 cp -rv ~/.config/sxhkd/* $WIDIR/xk/
	 cp -rv ~/.config/warpd/config $WIDIRCFGDIR/warpd.config
	 cp -rv ~/.config/hints/config.json $WIDIRCFGDIR/config.hints.json
	 cp -rv ~/.config/dunst/dunstrc $WIDIRCFGDIR/
	 cp -rv ~/.config/polybar/config.ini $WIDIRCFGDIR/polybar.config.ini
	 cp -rv ~/.local/bin/foxtag $WIDIRCFGDIR/
	 cp -rv ~/.config/dmenu-frecency/config.json $WIDIRCFGDIR/dmenu-frecency.config.json
	 cp -rv ~/.config/polybar/config.ini $WIDIRCFGDIR/polybar.config.ini 
	 cp -rv ~/.Xresources_nhk $WIDIRCFGDIR/
	 cp -rv ~/.config/lf/lfrc $WIDIRCFGDIR/
	 cp -rv ~/.config/mimi/mime.conf $WIDIRCFGDIR/
	 cp -rv ~/.nhktx.conf $WIDIRCFGDIR/
	 cp -rv ~/.local/bin/lfp $WIDIRCFGDIR/
	 cp -rv ~/.local/bin/foxtag $WIDIR/xt/
	 cp -rv ~/.local/bin/wiconv $WIDIR/xt/
	 cp -rv ~/.local/bin/slmenu $WIDIR/xt/
	 cp -rv ~/.config/hints/config.json $WIDIRCFGDIR/config.hints.json 
	;;

  -upk)  
	 wideps $2
   	 cd $WIDIR/src/xtr
	 cd $WIDIR/src/xtr/dmenu/ && make -j4 && sudo make install
	 cd ..
	 cd $WIDIR/src/xtr/lock/ && make -j4 && sudo make install
	 cd ..
	 cd $WIDIR/src/xtr/nsxiv/ && make -j4 && sudo make install
	 cd ..
	 cd $WIDIR/src/xtr/dunst/ && make -j4 && sudo make install
	 cd ..
	 cd $WIDIR/src/xtr/sxhkd/ && make -j4 && sudo make install
	 cd ..
	 cd $WIDIR/src/xtr/slstatus/ && make -j4 && sudo make install
	 cd ..
	 cd $WIDIR/src/xtr/surf/ && make -j4 && sudo make install
	 cd $WIDIR/src/xtr/surf/wyebadblock/ && make -j4 && sudo make install
	 sudo mkdir /usr/local/lib/surf && sudo ln -s /usr/lib/wyebrowser/adblock.so /usr/local/lib/surf
	 cd $WIDIR
	 mkdir -p $HOME/.config/nhk
	 sudo cp -rv $WIDIR/yr/lb /usr/bin 
	 sudo cp -rv $WIDIR/yr/wm /usr/bin 
	 sudo chmod +x /usr/bin/wm 
	 sudo chmod +x /usr/bin/lb 
	 mkdir -p ~/.config/polybar/
	 mkdir -p ~/.config/dmenu-frecency/ 
	 cp -rv $WIDIRCFGDIR/dmenu-frecency.config.json ~/.config/dmenu-frecency/config.json
	 mkdir -p ~/.config/dunst/
	 cp -rv $WIDIRCFGDIR/dunstrc ~/.config/dunst/
	 mkdir -p ~/.config/hints/
	 cp -rv $WIDIRCFGDIR/config.hints.json ~/.config/hints/config.json
	 mkdir -p ~/.config/warpd/
	 cp -rv $WIDIRCFGDIR/warpd.config ~/.config/warpd/config 
	 mkdir -p ~/.config/sxhkd && cp -rv $WIDIR/xk/* ~/.config/sxhkd/
	 cd $WIDIR
	 mkdir -p ~/.config/mimi 
	 cp -rv $WIDIRCFGDIR/mimi.conf ~/.config/mimi/mime.conf
	 mkdir -p ~/.local/bin 
	 cp -rv xt/foxtag ~/.local/bin/
	 cp -rv xt/wiconv ~/.local/bin/
         cp -rv xt/slmenu ~/.local/bin/
	 cp -rv $WIDIRCFGDIR/.Xresources_nhk $HOME/
	 xrdb -merge ~/.Xresources_nhk
	 git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
	 cp -rv $WIDIRCFGDIR/.nhktx.conf ~/
	 tmux source-file ~/.nhktx.conf
	 cd $WIDIR/src
         sudo make clean install
	 sudo mkdir -p /usr/share/xsessions/ 
	 sudo cp -rv $WIDIR/src/nhk.desktop /usr/share/xsessions/
	 sudo chmod +x patch/dwmc
	 sudo cp -rv patch/dwmc /usr/bin/dwmc
	 cd $WIDIR
         ;;

   -rb)
	 cd $WIDIR/src
         sudo make clean install
	 sudo mkdir -p /usr/share/xsessions/
	 sudo cp -rv $WIDIR/src/nhk.desktop /usr/share/xsessions/
	 cd $WIDIR
         ;;

   -EE)

     if [[ $# -gt 1 ]]; then
	$LABYREDIT "${@:2}" 
     else 
	sudo $LABYREDIT $(which wm) 
     fi

     ;;
	
esac 
