#!/bin/bash

MODE="K: "
def=""

set -e 

get_mode() {
   kmode=$(lb -H)

   echo "$kmode"
}

get_mode
#pid=$!
#interval=4
#for ((i=0; i<interval; i++)); do
#	sleep 1 &
#	lpid=$!
#	wait $lpid
#	if ! kill -0 $pid 2>/dev/null; then
#		break
#	fi
#done
#
#kill -9 $lpid 2>/dev/null	
