/* Bar functionality */
#include "bar_indicators.c"
#include "bar_tagicons.c"
#include "bar.c"

#include "bar_ewmhtags.c"
#include "combo.c"
#include "bar_launcher.c"
#include "bar_ltsymbol.c"
#include "bar_status.c"
#include "bar_tagpreview.c"
#include "bar_tags.c"
#include "bar_wintitle.c"
#include "bar_awesomebar.c"
#include "bar_systray.c"
#include "bar_wintitleactions.c"

/* Other patches */
#include "attachx.c"
#include "recttoclient.c"
#include "cfacts.c"
#include "cmdcustomize.c"
#include "cool_autostart.c"
#include "distributetags.c"
#include "dragcfact.c"
#include "dwmc.c"
#include "focusdir.c"
#include "focusfollowmouse.c"
#include "focusmaster.c"
#include "focusurgent.c"
#include "games.c"
#include "ipc.c"
#ifdef VERSION
#include "ipc/IPCClient.c"
#include "ipc/yajl_dumps.c"
#include "ipc/ipc.c"
#include "ipc/util.c"
#endif
#include "killunsel.c"
#include "maximize.c"
#include "movecenter.c"
#include "pertag.c"
#include "placedir.c"
#include "placemouse.c"
#include "push.c"
#include "reorganizetags.c"
#include "restartsig.c"
#include "riodraw.c"
#include "selfrestart.c"
#include "swallow.c"
#include "tagall.c"
#include "toggletopbar.c"
#include "transfer.c"
#include "vanitygaps.c"
#include "warp.c"
#include "zoomswap.c"
#include "xkb.c"
#include "xresources.c"
#include "seamless_restart.c"
/* Layouts */
#include "layout_facts.c"
#include "layout_centeredmaster.c"
#include "layout_monocle.c"
#include "layout_tile.c"

