/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_ewmhtags.h"
#include "combo.h"
#include "bar_launcher.h"
#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_tags.h"
#include "bar_wintitle.h"
#include "bar_awesomebar.h"
#include "bar_systray.h"
#include "bar_wintitleactions.h"

/* Other patches */
#include "attachx.h"
#include "recttoclient.h"
#include "banish.h"
#include "cfacts.h"
#include "cool_autostart.h"
#include "dwmc.h"
#include "focusdir.h"
#include "focusfollowmouse.h"
#include "focusmaster.h"
#include "focusurgent.h"
#include "games.h"
#include "ipc.h"
#include "ipc/ipc.h"
#include "ipc/util.h"
#include "killunsel.h"
#include "maximize.h"
#include "movecenter.h"
#include "pertag.h"
#include "placedir.h"
#include "placemouse.h"
#include "push.h"
#include "reorganizetags.h"
#include "riodraw.h"
#include "seamless_restart.h"
#include "selfrestart.h"
#include "swallow.h"
#include "vanitygaps.h"
#include "warp.h"
#include "zoomswap.h"
#include "xkb.h"
#include "xresources.h"
/* Layouts */
#include "layout_centeredmaster.h"
#include "layout_monocle.h"
#include "layout_tile.h"

